apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lRWXF4YytpWitPY3R5ZjB0S0ZLNEZSekFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5emEzVndjR1Z5TFhOcGRHVXRZMkV3SGhjTk1qVXdOREV3TURjME1qTXhXaGNOTXpBdwpOREE1TURjME1qTXhXakFhTVJnd0ZnWURWUVFERXc5emEzVndjR1Z5TFhOcGRHVXRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNqYnFqZi90RWRobWpWSkRjZld4azJiT01OSFdLTzhBcFIKOTdyVkNzSUN3eW52engvQ3lGN2xYR3hkc2diR3Zwb3FENDl4Rkt3U0h1Ry9HaUVrYzBreWIrVGwyanNrVHNnbQo2OXNZN0ZQRTRjcDNCZW9nd2xsL3ZVdEVvRy8xZHlwMnNLcE5Ya1RwQUhXMWFqMzFneFRZQ3I4eEhTREt3dFZjCk55dG1hQ1hiYkpWUHNnczJmMEptUVdvaFMzenpCbWZXNk1HaFZ5SUJKZnVDV3dlOHVtK0ZrRy9Pb0F1VEJRSVIKbWxjNjJWeFJibVNZcHRoM3Q3aEZuYS8zUEltY0tXVHRNS0l5YkVqYWJPczRhOUovSWZvM2l1bSswdzhGMnJnWgpscm9qZCtjMkkxK1VqWXd2M25DVGUvVWxnajk0ZU85QW43RnUxam9nL0cvRmNRVEFHZ3haQWdNQkFBR2piakJzCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUnl2UHAxd2JybEFyckYzbmlwZTllNEI2YVFVdwpDd1lEVlIwUkJBUXdBb0lBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCeUtFN1VSK0pIWHNOdlArUzZLRVlvCnppV0g3WnFNcDk3VmNUOEl0RUhMUjkvYkJSME9rdmpzK3RCdEd1NWl6ZStnRk5JV1RJUWJPc0liVVRDNlFYbjkKazBDamV5QmRoeXhMTFcwS2t5cUZBSk9HUDBoanljN1MrV1pBTFhaYytzVGRtRFNqcTJFL05OZGxiYzBsYW1mVQo2YXZBbGZxNTVZN3ZFOVV1V3NwOHNVcHIwSExHaVhLSW5Kdm5ubFN0Vm9JRHlWUDgzdkZQV2ttelBpRzV1RjZmCmFsL3NkcTRZemNXTVdDb3VQandHazFjTm1aeDVBcWdPSjZrZnVPMmp0WWNsMFJ1NUdVM3QrQ3k3UC8yejdpRzQKdFRnRlBrQ3lsTW43S1d6anMyc2Z6ZVZ2YWVBVTNQMERqbEpjd04vUlo1cUJBZkpqQ3hWdTNQMXBuTHIwSHRINAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  password: OWVaMUxHWGVlbm5rdDNIdW43N1RETzhl
kind: Secret
metadata:
  annotations:
    skupper.io/claim-expiration: "2025-04-11T05:01:14+09:00"
    skupper.io/generated-by: 7eb5645b-15c9-467f-89c0-0dbcd3ac3182
    skupper.io/site-version: 1.8.3
    skupper.io/url: https://claims-quarkuscoffeeshop-demo.apps.cluster-r2tkq.r2tkq.sandbox657.opentlc.com:443/7633ce4a-1644-11f0-bd23-fa464c758e2a
  creationTimestamp: null
  labels:
    skupper.io/type: token-claim
  name: 7633ce4a-1644-11f0-bd23-fa464c758e2a
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: 7eb5645b-15c9-467f-89c0-0dbcd3ac3182
