apiVersion: skupper.io/v2alpha1
kind: AccessToken
metadata:
  name: skupper-asite-82f8ca89-9c45-4ad0-a6f0-f5f1fd4a9778
spec:
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIDNzCCAh+gAwIBAgIRAOASdJKVtMS9h+W/SEUkJkkwDQYJKoZIhvcNAQELBQAw
    HzEdMBsGA1UEAxMUU2t1cHBlckdyYW50U2VydmVyQ0EwHhcNMjUwNDI1MDAzMTQ0
    WhcNMzAwNDI0MDAzMTQ0WjAfMR0wGwYDVQQDExRTa3VwcGVyR3JhbnRTZXJ2ZXJD
    QTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9yhionwJJtwVLFJZwj
    4S2yrucV9xk07VH2LApYWvNsa7B7YGme6VDRl9jTSGjGOSfMziDIkpm2tej2di0y
    2Y2utGrKb8dtjWYXvgiSz+oLtt/fTO1MdSQ1c02J2otmZhtERsUBIPX9JJ7NU1ja
    6QCYSCX+HMIN7n2qkE2CkGFu0kuN5mKCsmcigno0eWieUoWJASNtsbcjofERIas5
    AeHJtrQ1+6iRx1VHYZSB9zj0jrOVVTVNt0qaL+RwsVs3bSItURRi1IBLUhTnCEf/
    hnoZdMilWqPZzz6Dsun2h3ig9LkvOKjDVSINAAt5pBBL0hV3cFnrlNkuId3psNWP
    6YECAwEAAaNuMGwwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSScTMjzjxkSa14
    assfVLY695/uejALBgNVHREEBDACggAwDQYJKoZIhvcNAQELBQADggEBAK22wO2m
    4ChfwDuz1iFmfk8Oq3t4ZeYsOGUIUNg4WzzCF1gYfXV9IMv6iKJmXfPHouzUQs/+
    kXQjVYoEFIYsywOie4C7TwgDpnT+EhznGAgFqYwH228jk3pRA6a9rFKjLXLIirUE
    SfzeoFmlvyiYksvSveWkO3JnriQUhvBvewzB8ZgHQ2YMhfZ0drPXVCfEgAFTa3Hy
    619Mj8sQ0FYymE4DoPUbSVXUh6O3pL5oAywHkY2w79posyMwqkWlGdkzSgWIFQdh
    xFSdpvrAB5ZP93CU33VTs7oOGZP71Iyb8UfE8GlfReIESOqmabFiK0UfFH/eSWN9
    uaBLPav6nCdWVPM=
    -----END CERTIFICATE-----
  code: mEAAw0QRCgGPruDwPlJDyTf8
  linkCost: 1
  url: https://a6709427dd12a45339236d6af7ac3d6a-366292098.us-east-2.elb.amazonaws.com:9090/f0b4366d-1f95-487c-8216-99789e239dde
