- name: Remove OpenShift Pipelines OperatorGroup
  kubernetes.core.k8s:
    state: absent
    namespace: openshift-operators
    definition: "{{ lookup('template', 'openshift-pipelines.yaml.j2') }}"
  ignore_errors: true
  tags: always

- name: Remove OpenShift gitops OperatorGroup
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'openshift-gitops.yaml.j2') }}"
  ignore_errors: true
  tags: always

- name: delete QuayRegistry quayecosystem
  command: oc delete QuayRegistry quayecosystem -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete quay crd
  command: oc delete crd quayecosystems.redhatcop.redhat.io -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete Red Hat Integration - AMQ Streams
  command:  oc delete csv "{{ amqstartingCSV }}" -n openshift-operators
  ignore_errors: true
  tags: always

- name: delete Crunchy Postgres for Kubernetes
  command:  oc delete csv "{{ crunchystartingCSV }}" -n openshift-operators
  ignore_errors: true
  tags: always

- name: delete Red Hat OpenShift GitOps 
  command:  oc delete csv "{{ gitopsoperatorCSV }}" -n openshift-operators
  ignore_errors: true
  tags: always

- name: delete Red Hat OpenShift Pipelines 
  command:  oc delete csv "{{ openshiftpipelinesCSV }}" -n openshift-operators
  ignore_errors: true
  tags: always

- name: delete openshift-gitops project
  command: oc delete project openshift-gitops
  ignore_errors: true
  tags: always

- name: delete development project
  command: "oc delete project {{ development_project }}"
  ignore_errors: true
  tags: always

- name: delete homeoffice project
  command: "oc delete project {{ homeoffice_project }}"
  ignore_errors: true
  tags: always

- name: delete quay-enterprise project
  command: "oc delete project {{ quay_project_name }}"
  ignore_errors: true
  tags: always