apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirrormaker2
  namespace: kafka-b
spec:
  version: 3.6.0
  replicas: 1
  connectCluster: "target"
  clusters:
  - alias: source
    bootstrapServers: kafka-cafe-a-bootstrap:9092
  - alias: target
    bootstrapServers: kafka-cafe-b-bootstrap:9092
  mirrors:
  - sourceCluster: source
    targetCluster: target
    topicsPattern: ".*"
    groupsPattern: ".*"
    sourceConnector:
      config:
        replication.factor: 1
        offset.syncs.topic.replication.factor: 1
        config.storage.replication.factor: 1
        status.storage.replication.factor: 1