apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2-extended
  namespace: quarkuscoffeeshop-demo
  labels:
    strimzi.io/name: cafe-cluster-kafka

spec:
  version: 3.9.0
  replicas: 1
  connectCluster: "cafe-bsite"
  clusters:
    - alias: "cafe-bsite"
      bootstrapServers: "external-cafe-cluster-kafka-bsite:9094"
    - alias: "cafe-asite"
      bootstrapServers: "external-cafe-cluster-kafka-asite:9094"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
      org.apache.kafka.connect.mirror.MirrorSourceConnector: "DEBUG"
      org.apache.kafka.connect.mirror.CheckpointTask: "DEBUG"
      org.apache.kafka.connect.mirror.HeartbeatTask: "DEBUG"
      org.apache.kafka.connect.mirror.MirrorClient: "DEBUG"
      org.apache.kafka.connect.mirror.OffsetSyncStore: "DEBUG"
  mirrors:
    - sourceCluster: "cafe-bsite"
      targetCluster: "cafe-asite"
      topicsPattern: "^(barista-in|kitchen-in|orders.*|web.*|inventory.*)$"
      groupsPattern: ".*"
      sourceConnector:
        enabled: true
        config:
          bootstrap.servers: "external-cafe-cluster-kafka-bsite:9094"
          replication.policy.class: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
          replication.policy.separator: "."
          consumer.fetch.min.bytes: "1"
          consumer.fetch.max.wait.ms: "10"
          producer.linger.ms: "0"
          producer.batch.size: "16384"
          emit.heartbeats.enabled: true
          emit.checkpoints.enabled: true
          sync.group.offsets.enabled: true
          sync.topic.acls.enabled: false
          refresh.topics.enabled: true
          refresh.groups.enabled: true
          auto.create.topics.enable: true
          security.protocol: PLAINTEXT
          producer.request.timeout.ms: 60000
          consumer.request.timeout.ms: 60000
          consumer.metadata.fetch.timeout.ms: 60000
          offset-syncs.topic.replication.factor: 1
          refresh.topics.interval.seconds: 10
          client.dns.lookup: use_all_dns_ips
          config.storage.topic: mirrormaker2-cluster-configs
          offset.storage.topic: mirrormaker2-cluster-offsets
          status.storage.topic: mirrormaker2-cluster-status
  template:
    connectContainer:
      env:
        - name: KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME
          value: "mm2-extended-mirrormaker2"
        - name: KAFKA_CONNECT_REST_PORT
          value: "8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkamirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkamirror
  template:
    metadata:
      labels:
        app: kafkamirror
    spec:
      containers:
        - name: kafkamirror
          image: confluentinc/cp-kafka:latest
          command:
            - /bin/sh
            - -c
            - |
              kafka-mirror-maker --consumer.config /etc/kafka/consumer.properties --producer.config /etc/kafka/producer.properties
          env:
            - name: MIRROR_MAKER_BOOTSTRAP_SERVERS
              value: "external-cafe-cluster-kafka-bsite:9092"
