apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: cafe-mm2
  namespace: quarkuscoffeeshop-demo
spec:
  version: 3.9.0
  replicas: 1
  connectCluster: "b-cluster"
  clusters:
    - alias: "a-cluster"
      bootstrapServers: "kafka-cafe-a-bootstrap:9092"
    - alias: "b-cluster"
      bootstrapServers: "external-kafka-cafe-b-bootstrap:9092"
  mirrors:
    - sourceCluster: "a-cluster"
      targetCluster: "b-cluster"
      topicsPattern: ".*"
      groupsPattern: ".*"
      config:
        replication.policy.class: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
        mirror.topic.name.separator: "-"
        
      