apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mirrormaker2-cluster-offsets
  labels:
    strimzi.io/cluster: cafe-cluster
spec:
  topicName: mirrormaker2-cluster-offsets
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mirrormaker2-cluster-status
  labels:
    strimzi.io/cluster: cafe-cluster
spec:
  topicName: mirrormaker2-cluster-status
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact