apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: cafe-mm2
  namespace: quarkuscoffeeshop-demo
spec:
  version: 3.9.0
  replicas: 1
  connectCluster: "cafe-asite-cluster"
  clusters:
    - alias: "cafe-bsite-cluster"
      bootstrapServers: "cafe-cluster-kafka-bootstrap:9092"
    - alias: "cafe-asite-cluster"
      bootstrapServers: "external-kafka-cafe-a-bootstrap:9092"
  mirrors:
    - sourceCluster: "cafe-bsite-cluster"
      targetCluster: "cafe-asite-cluster"
      topicsPattern: ".*"
      groupsPattern: ".*"
      config:
        replication.policy.class: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
        replication.policy.separator: "."
        refresh.topics.enabled: true
        refresh.groups.enabled: true
        sync.topic.acls.enabled: false
        emit.heartbeats.enabled: true
        # タイムアウトの設定を追加（Skupper）
        request.timeout.ms: 120000  # 120秒
        metadata.fetch.timeout.ms: 120000
        retry.backoff.ms: 10000
        consumer.request.timeout.ms: 90000
        consumer.metadata.fetch.timeout.ms: 90000
        producer.request.timeout.ms: 90000
        reconnect.backoff.max.ms: 60000