apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quarkuscoffeeshop-cicd-operatorgroup
  namespace: quarkuscoffeeshop-cicd
spec:
  targetNamespaces:
    - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installMode: AllNamespaces
---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
