# skupper-operatorgroup.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: skupper-operator-group
  namespace: quarkuscoffeeshop-demo
spec:
  targetNamespaces:
    - quarkuscoffeeshop-demo
---
# skupper-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-service-interconnect
  namespace: quarkuscoffeeshop-demo
spec:
  name: skupper-operator
  channel: stable-2
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic